// lib/core4/counterfactual.ts
//
// Measure what a conclusion rests on, instead of asserting it.
//
// WHY THIS EXISTS, AND WHY EVERYTHING BEFORE IT WAS PROMPT-REPRODUCIBLE.
// An adversarial audit (docs/CORE-4-ARCHITECTURE.md §5″) put one question to
// every Core 4 subsystem: could a single good system prompt, given the same
// frontier model and the same transcript, produce the same observable
// behaviour? Nineteen remainders were claimed and sixteen were refuted. The
// refuted sixteen had one thing in common, and it is the whole lesson:
//
//   EVERY ONE OF THEM RE-READ THE TRANSCRIPT THE REPLY MODEL ALREADY HELD.
//
// The state reader, the problem model, the detectors, the allocator — all of
// them are a weaker model reading text a stronger model has in front of it.
// You cannot beat a model at reading by reading harder. The three survivors
// were all cases where Socria held information the transcript does not
// contain: an out-of-band correction, an explicitly corrected field, recall
// from beyond the context window.
//
// So the rule this module follows: stop reading, and generate information
// that does not exist yet. With API access only, there is exactly one
// instrument for that — running the model on inputs the conversation never
// contained.
//
// WHAT IT DOES. `problem.ts` builds "X rests on Y" edges from a cheap model's
// guess about the transcript. That is an assertion; it is reproducible by a
// prompt; and E16 exists because it is not even stable run to run (the same
// conversation produced 0 relations in run 8 and 3 in run 9). This module
// instead ABLATES a premise — removes it from the set and asks what now
// follows — and reports whether the conclusion moved.
//
//   "Your March timeline survives dropping the churn assumption. It does not
//    survive the Q4 renewal date: without that the schedule moves to June."
//
// No prompt produces that sentence at any length, because producing it
// requires executing the model against a premise set the person never wrote.
// That is information generated by intervention, not recalled from context —
// which also means it pays off on turn one and does not wait for a long
// conversation.
//
// HONESTY ABOUT THE INSTRUMENT. The ablation runs on the cheap model, which
// is weaker than the one writing the reply. That is tolerable here in a way
// it is not for the detectors, because the question is far narrower: not
// "what should be said" but "does this conclusion still follow without this
// premise". Even so, every verdict carries its own confidence, anything below
// CF_FLOOR is discarded rather than reported, and an 'unclear' answer is
// never rendered as robustness. A premise we could not test is not a premise
// we tested and cleared.

import type { ProblemItem, ProblemModel } from './problem';
import type { CognitiveState } from '../cognition/state';
import { modelClient, type ModelClient } from './model';
import { COGNITION_MODEL } from '../cognition/engine';

/** Below this the ablation told us nothing and is dropped, not reported. */
export const CF_FLOOR = 0.55;

/** How many premises are worth the calls. Four is two seconds of parallel work. */
export const MAX_ABLATIONS = 4;

export type Dependence = 'load_bearing' | 'robust' | 'unclear';

export interface Ablation {
  /** the premise that was removed */
  premiseId: string;
  premise: string;
  /** did the conclusion survive without it? */
  dependence: Dependence;
  /** what follows instead, when it does not survive */
  instead: string;
  confidence: number;
  /** the epistemic standing of the premise itself — an unchecked load-bearing one is the prize */
  standing: string;
}

export interface Counterfactual {
  /** the conclusion under test, in the person's own terms */
  conclusion: string;
  conclusionId: string;
  ablations: Ablation[];
  /** calls actually made */
  tested: number;
}

const SYSTEM = `You test whether a conclusion still follows when one of its premises is removed.

You are given a CONCLUSION someone has reached, the PREMISES they are working from, and ONE premise to REMOVE.

Reason only from the premises that remain. Do not supply outside facts, do not repair the gap with your own knowledge, and do not judge whether the conclusion is wise — only whether it still FOLLOWS.

Return JSON with exactly these fields:

holds       true | false | "unclear"
            true    — the conclusion still follows without the removed premise
            false   — it does not; something else follows, or nothing does
            "unclear" — you genuinely cannot tell from what remains
instead     one line: what follows INSTEAD, when holds is false. "" otherwise.
            Be specific and quantitative where the premises are.
confidence  0-1, how sure you are of that verdict

"unclear" is a good answer. A premise you cannot evaluate is not a premise you have cleared.`;

const ask = (conclusion: string, premises: readonly string[], removed: string) =>
  `CONCLUSION:\n${conclusion}\n\nPREMISES (the removed one is NOT listed — reason only from these):\n${
    premises.map((p) => `- ${p}`).join('\n') || '- (none remain)'
  }\n\nREMOVED PREMISE (treat as unknown, not as false):\n- ${removed}`;

function sanitize(raw: unknown): { dependence: Dependence; instead: string; confidence: number } {
  const o = (raw ?? {}) as Record<string, unknown>;
  const h = o.holds;
  const dependence: Dependence = h === true ? 'robust' : h === false ? 'load_bearing' : 'unclear';
  const c = typeof o.confidence === 'number' && Number.isFinite(o.confidence) ? Math.min(1, Math.max(0, o.confidence)) : 0;
  const instead = typeof o.instead === 'string' ? o.instead.trim().slice(0, 300) : '';
  return { dependence, instead, confidence: c };
}

/**
 * The conclusion worth testing: what the person has actually landed on.
 *
 * A decision beats a conclusion beats a claim, because the further along it
 * is the more it costs to have it rest on something unchecked. Socria's own
 * claims are never the target — testing our own reasoning back at them is
 * navel-gazing, and the person did not ask for it.
 */
export function targetOf(p: ProblemModel): ProblemItem | null {
  const mine = (i: ProblemItem) => i.owner === 'user' || i.owner === 'unknown';
  const byKind = (k: ProblemItem['kind']) => p.live.filter((i) => i.kind === k && mine(i)).sort((a, b) => b.turn - a.turn)[0];
  return byKind('decision') ?? byKind('conclusion') ?? byKind('claim') ?? null;
}

/**
 * Premises worth ablating, most informative first.
 *
 * An ASSUMED or UNCHECKED premise that turns out to be load-bearing is the
 * whole point of the exercise, so those go first. A premise the conclusion is
 * already recorded as depending on is next, because confirming a recorded
 * edge is cheap and disconfirming one is valuable. Everything else is
 * background the person is unlikely to thank us for testing.
 */
export function candidates(p: ProblemModel, target: ProblemItem): ProblemItem[] {
  const pool = p.live.filter(
    (i) => i.id !== target.id && i.text.trim().length > 12 && i.kind !== 'question' && i.kind !== 'uncertainty'
  );
  const rank = (i: ProblemItem) => {
    let r = 0;
    if (i.epistemic === 'assumed') r += 4;
    if (i.epistemic === 'needs_verification') r += 3;
    if (i.epistemic === 'inferred') r += 1;
    if (target.dependsOn.includes(i.id)) r += 2;
    if (target.supportedBy.includes(i.id)) r += 2;
    if (i.kind === 'constraint' || i.kind === 'evidence') r += 1;
    return r;
  };
  return pool
    .map((i) => ({ i, r: rank(i) }))
    .filter((x) => x.r > 0)
    .sort((a, b) => b.r - a.r || b.i.turn - a.i.turn)
    .slice(0, MAX_ABLATIONS)
    .map((x) => x.i);
}

/**
 * Run the ablations, in parallel, and keep only what they actually settled.
 *
 * Fails to `null` rather than throwing or guessing: a turn is never worse for
 * this having been unavailable, which is the same failure direction every
 * other optional stage takes (docs/CORE-4-ARCHITECTURE.md §1).
 */
export async function testDependencies(
  apiKey: string,
  p: ProblemModel,
  _state: Pick<CognitiveState, 'currentFocus'>,
  client?: ModelClient
): Promise<Counterfactual | null> {
  const target = targetOf(p);
  if (!target) return null;
  const probe = candidates(p, target);
  if (!probe.length) return null;
  // The conclusion is NOT one of its own premises. Without this, the ablation
  // prompt listed the target inside the premise list it was told to reason
  // from — "does X follow from {X, Y}" — which is trivially yes, so every
  // ablation came back `robust` and no load-bearing premise could ever be
  // found. Caught by dumping the prompt actually sent.
  const all = p.live.filter((i) => i.id !== target.id).map((i) => i.text);
  const c = client ?? modelClient(apiKey);

  const runs = await Promise.all(
    probe.map(async (premise): Promise<Ablation | null> => {
      try {
        const remaining = all.filter((t) => t !== premise.text);
        const res = await c.complete({
          role: 'verify',
          model: COGNITION_MODEL,
          temperature: 0,
          json: true,
          system: SYSTEM,
          messages: [{ role: 'user', content: ask(target.text, remaining, premise.text) }],
          maxTokens: 300,
        });
        const v = sanitize(JSON.parse(res.text || '{}'));
        if (v.confidence < CF_FLOOR || v.dependence === 'unclear') return null;
        // A conclusion that "does not follow" with nothing to say about what
        // does is a shrug wearing a verdict's clothes.
        if (v.dependence === 'load_bearing' && !v.instead) return null;
        return {
          premiseId: premise.id,
          premise: premise.text,
          dependence: v.dependence,
          instead: v.instead,
          confidence: v.confidence,
          standing: premise.epistemic,
        };
      } catch {
        return null;
      }
    })
  );

  const ablations = runs.filter((a): a is Ablation => a !== null);
  if (!ablations.length) return null;
  return { conclusion: target.text, conclusionId: target.id, ablations, tested: probe.length };
}

/**
 * What the measurement earned the right to say.
 *
 * Only the load-bearing ones, and only where the premise itself is shaky —
 * "your conclusion depends on a fact you have checked" is true of every sound
 * argument and is not worth a sentence. The valuable shape is narrow: THIS
 * conclusion falls over without THAT, and THAT is an assumption nobody has
 * been back to.
 *
 * Robust results are rendered too, but as one clause, because "it survives
 * without X" is genuinely useful to someone about to go and verify X — it
 * tells them not to bother.
 */
export function renderCounterfactual(cf: Counterfactual | null): string {
  if (!cf) return '';
  const shaky = new Set(['assumed', 'needs_verification', 'inferred', 'unknown']);
  const load = cf.ablations.filter((a) => a.dependence === 'load_bearing');
  const firm = cf.ablations.filter((a) => a.dependence === 'robust' && shaky.has(a.standing));
  if (!load.length && !firm.length) return '';
  const lines: string[] = [];
  for (const a of load.slice(0, 2)) {
    const mark = a.standing === 'assumed' ? ' (which is an assumption, not a finding)' : a.standing === 'needs_verification' ? ' (which nothing has checked)' : '';
    lines.push(`  - Remove "${a.premise}"${mark} and "${cf.conclusion}" no longer follows — instead: ${a.instead}`);
  }
  for (const a of firm.slice(0, 1)) {
    lines.push(`  - "${cf.conclusion}" holds even without "${a.premise}", so that one is not worth chasing.`);
  }
  return (
    `\n=== Tested, not assumed: what this actually rests on ===\n${lines.join('\n')}\n` +
    `This was measured by removing each premise and re-deriving, not inferred from how they wrote it. ` +
    `Where it changes what they should do next, say it plainly and in your own words — what falls over, and what they would have to check to know. ` +
    `Never describe the test, the removal, or that anything was run: they want the finding, not the method.\n`
  );
}

// ── MEASURED CONTRADICTION ──────────────────────────────────────────
//
// The audit's sharpest finding about the detector family: `contradiction()`
// in contribution.ts fires only from a `contradicts` edge, and that edge
// exists only when the 2-second cheap reader already spotted the
// contradiction itself. So the "detector" re-packages the reader's finding
// and adds nothing — and a frontier model reading the same transcript does
// the hard part better. It is a weaker model's assertion wearing a
// measurement's clothes.
//
// This replaces the assertion with a test, and it does two things the
// asserted version could not:
//
//   1. It CONFIRMS. Asked directly whether two statements can both hold under
//      the same reading, a model refutes most candidate pairs — people
//      qualify, rescope and change their minds, and almost none of that is a
//      contradiction. The asserted edge had no such filter.
//   2. It FINDS PAIRS THE READER MISSED. Candidates come from the structure
//      too, not only from reader edges: two live statements from different
//      turns, about the same subject, carrying different numbers. That is
//      exactly the shape the reader is worst at, because the two statements
//      are far apart in a long transcript.
//
// Cost is gated like every other measurement here: at most 3 pairs, only on a
// turn where the answer could change the reply.

export interface ContradictionTest {
  aId: string;
  bId: string;
  a: string;
  b: string;
  /** turns apart — the whole value is in pairs nobody put side by side */
  distance: number;
  conflict: string;
  confidence: number;
  /** did the reader already claim this pair, or did the structure find it? */
  source: 'reader' | 'structure';
}

const CONTRA_SYSTEM = `You are given two statements a person made at different points in one conversation.

Decide whether they can BOTH be true at the same time, under the same reading of the words.

Be strict about what counts as a contradiction:
- A person REFINING, RESCOPING or CHANGING THEIR MIND is not a contradiction. "Churn is 4%" then "churn is 3.6% after the rebuild" is an update, not a conflict.
- Two claims about DIFFERENT things, different time periods, different populations or different conditions are not a contradiction, even when the words are similar.
- Vagueness is not contradiction. If one statement is loose enough to be compatible, they are compatible.
- It IS a contradiction when both are presented as currently true and one being true makes the other false.

Return JSON with exactly these fields:

compatible   true | false | "unclear"
conflict     one line: the precise thing that cannot hold both ways. "" when compatible.
confidence   0-1

Default to compatible. Calling an update or a rescoping a contradiction is the failure that matters here: it tells the person they contradicted themselves when they did not.`;

const contraAsk = (a: string, aTurn: number, b: string, bTurn: number) =>
  `STATEMENT A (turn ${aTurn}):\n${a}\n\nSTATEMENT B (turn ${bTurn}):\n${b}`;

const NUM = /-?\d+(?:\.\d+)?/g;
const STOPISH = new Set(['the', 'and', 'that', 'this', 'with', 'from', 'about', 'into', 'over', 'than', 'then', 'they', 'them', 'what', 'when', 'will', 'would', 'have', 'has', 'was', 'are', 'for', 'our', 'their']);
const topic = (t: string): Set<string> =>
  new Set(t.toLowerCase().split(/[^a-z]+/).filter((w) => w.length > 3 && !STOPISH.has(w)));

/**
 * Pairs worth the call: reader-claimed ones first, then the ones the reader is
 * structurally worst at — same subject, different numbers, turns apart.
 */
export function contradictionCandidates(p: ProblemModel): { a: ProblemItem; b: ProblemItem; source: 'reader' | 'structure' }[] {
  const live = p.live.filter((i) => i.kind !== 'question' && i.kind !== 'uncertainty' && i.text.trim().length > 15);
  const seen = new Set<string>();
  const out: { a: ProblemItem; b: ProblemItem; source: 'reader' | 'structure' }[] = [];
  const key = (a: ProblemItem, b: ProblemItem) => [a.id, b.id].sort().join('|');

  for (const a of live) {
    for (const id of a.contradicts) {
      const b = p.items.find((i) => i.id === id);
      if (!b || b.settled || seen.has(key(a, b))) continue;
      seen.add(key(a, b));
      out.push({ a, b, source: 'reader' });
    }
  }
  for (let i = 0; i < live.length; i++) {
    for (let j = i + 1; j < live.length; j++) {
      const a = live[i];
      const b = live[j];
      if (seen.has(key(a, b)) || Math.abs(a.turn - b.turn) < 2) continue;
      const ta = topic(a.text);
      const tb = topic(b.text);
      let shared = 0;
      for (const w of ta) if (tb.has(w)) shared += 1;
      if (shared < 2) continue;
      const na = a.text.match(NUM) ?? [];
      const nb = b.text.match(NUM) ?? [];
      // Different numbers about the same subject is the shape worth a call.
      if (!na.length || !nb.length || na.join() === nb.join()) continue;
      seen.add(key(a, b));
      out.push({ a, b, source: 'structure' });
    }
  }
  return out.sort((x, y) => Math.abs(y.a.turn - y.b.turn) - Math.abs(x.a.turn - x.b.turn)).slice(0, 3);
}

/** Test the candidate pairs, keep only what came back as a real conflict. */
export async function testContradictions(
  apiKey: string,
  p: ProblemModel,
  client?: ModelClient
): Promise<ContradictionTest[]> {
  const pairs = contradictionCandidates(p);
  if (!pairs.length) return [];
  const c = client ?? modelClient(apiKey);
  const runs = await Promise.all(
    pairs.map(async ({ a, b, source }): Promise<ContradictionTest | null> => {
      try {
        const res = await c.complete({
          role: 'verify',
          model: COGNITION_MODEL,
          temperature: 0,
          json: true,
          system: CONTRA_SYSTEM,
          messages: [{ role: 'user', content: contraAsk(a.text, a.turn, b.text, b.turn) }],
          maxTokens: 250,
        });
        const o = JSON.parse(res.text || '{}') as Record<string, unknown>;
        const conf = typeof o.confidence === 'number' && Number.isFinite(o.confidence) ? Math.min(1, Math.max(0, o.confidence)) : 0;
        const conflict = typeof o.conflict === 'string' ? o.conflict.trim().slice(0, 300) : '';
        if (o.compatible !== false || conf < CF_FLOOR || !conflict) return null;
        return { aId: a.id, bId: b.id, a: a.text, b: b.text, distance: Math.abs(a.turn - b.turn), conflict, confidence: conf, source };
      } catch {
        return null;
      }
    })
  );
  return runs.filter((r): r is ContradictionTest => r !== null);
}

export function renderContradictions(found: readonly ContradictionTest[]): string {
  if (!found.length) return '';
  const top = found.slice(0, 2);
  const lines = top.map((f) => `  - "${f.a}" and "${f.b}" (${f.distance} turns apart): ${f.conflict}`);
  return (
    `\n=== Checked, and they do conflict ===\n${lines.join('\n')}\n` +
    `Each pair was tested directly for whether both can hold, and each came back that they cannot — this is not a guess from how they worded it. ` +
    `Raise at most one, where it bears on what they are deciding, in your own words. ` +
    `Do not say it was checked, tested or noticed across turns: say what conflicts.\n`
  );
}
