// lib/core4/counterfactual.ts
//
// Measure what a conclusion rests on, instead of asserting it.
//
// WHY THIS EXISTS, AND WHY EVERYTHING BEFORE IT WAS PROMPT-REPRODUCIBLE.
// An adversarial audit (docs/CORE-4-ARCHITECTURE.md §5″) put one question to
// every Core 4 subsystem: could a single good system prompt, given the same
// frontier model and the same transcript, produce the same observable
// behaviour? Nineteen remainders were claimed and sixteen were refuted. The
// refuted sixteen had one thing in common, and it is the whole lesson:
//
//   EVERY ONE OF THEM RE-READ THE TRANSCRIPT THE REPLY MODEL ALREADY HELD.
//
// The state reader, the problem model, the detectors, the allocator — all of
// them are a weaker model reading text a stronger model has in front of it.
// You cannot beat a model at reading by reading harder. The three survivors
// were all cases where Socria held information the transcript does not
// contain: an out-of-band correction, an explicitly corrected field, recall
// from beyond the context window.
//
// So the rule this module follows: stop reading, and generate information
// that does not exist yet. With API access only, there is exactly one
// instrument for that — running the model on inputs the conversation never
// contained.
//
// WHAT IT DOES. `problem.ts` builds "X rests on Y" edges from a cheap model's
// guess about the transcript. That is an assertion; it is reproducible by a
// prompt; and E16 exists because it is not even stable run to run (the same
// conversation produced 0 relations in run 8 and 3 in run 9). This module
// instead ABLATES a premise — removes it from the set and asks what now
// follows — and reports whether the conclusion moved.
//
//   "Your March timeline survives dropping the churn assumption. It does not
//    survive the Q4 renewal date: without that the schedule moves to June."
//
// No prompt produces that sentence at any length, because producing it
// requires executing the model against a premise set the person never wrote.
// That is information generated by intervention, not recalled from context —
// which also means it pays off on turn one and does not wait for a long
// conversation.
//
// HONESTY ABOUT THE INSTRUMENT. The ablation runs on the cheap model, which
// is weaker than the one writing the reply. That is tolerable here in a way
// it is not for the detectors, because the question is far narrower: not
// "what should be said" but "does this conclusion still follow without this
// premise". Even so, every verdict carries its own confidence, anything below
// CF_FLOOR is discarded rather than reported, and an 'unclear' answer is
// never rendered as robustness. A premise we could not test is not a premise
// we tested and cleared.

import type { ProblemItem, ProblemModel } from './problem';
import type { CognitiveState } from '../cognition/state';
import { modelClient, type ModelClient } from './model';
import { COGNITION_MODEL } from '../cognition/engine';

/** Below this the ablation told us nothing and is dropped, not reported. */
export const CF_FLOOR = 0.55;

/** How many premises are worth the calls. Four is two seconds of parallel work. */
export const MAX_ABLATIONS = 4;

export type Dependence = 'load_bearing' | 'robust' | 'unclear';

export interface Ablation {
  /** the premise that was removed */
  premiseId: string;
  premise: string;
  /** did the conclusion survive without it? */
  dependence: Dependence;
  /** what follows instead, when it does not survive */
  instead: string;
  confidence: number;
  /** the epistemic standing of the premise itself — an unchecked load-bearing one is the prize */
  standing: string;
}

export interface Counterfactual {
  /** the conclusion under test, in the person's own terms */
  conclusion: string;
  conclusionId: string;
  ablations: Ablation[];
  /** calls actually made */
  tested: number;
}

const SYSTEM = `You test whether a conclusion still follows when one of its premises is removed.

You are given a CONCLUSION someone has reached, the PREMISES they are working from, and ONE premise to REMOVE.

Reason only from the premises that remain. Do not supply outside facts, do not repair the gap with your own knowledge, and do not judge whether the conclusion is wise — only whether it still FOLLOWS.

Return JSON with exactly these fields:

holds       true | false | "unclear"
            true    — the conclusion still follows without the removed premise
            false   — it does not; something else follows, or nothing does
            "unclear" — you genuinely cannot tell from what remains
instead     one line: what follows INSTEAD, when holds is false. "" otherwise.
            Be specific and quantitative where the premises are.
confidence  0-1, how sure you are of that verdict

"unclear" is a good answer. A premise you cannot evaluate is not a premise you have cleared.`;

const ask = (conclusion: string, premises: readonly string[], removed: string) =>
  `CONCLUSION:\n${conclusion}\n\nPREMISES (the removed one is NOT listed — reason only from these):\n${
    premises.map((p) => `- ${p}`).join('\n') || '- (none remain)'
  }\n\nREMOVED PREMISE (treat as unknown, not as false):\n- ${removed}`;

function sanitize(raw: unknown): { dependence: Dependence; instead: string; confidence: number } {
  const o = (raw ?? {}) as Record<string, unknown>;
  const h = o.holds;
  const dependence: Dependence = h === true ? 'robust' : h === false ? 'load_bearing' : 'unclear';
  const c = typeof o.confidence === 'number' && Number.isFinite(o.confidence) ? Math.min(1, Math.max(0, o.confidence)) : 0;
  const instead = typeof o.instead === 'string' ? o.instead.trim().slice(0, 300) : '';
  return { dependence, instead, confidence: c };
}

/**
 * The conclusion worth testing: what the person has actually landed on.
 *
 * A decision beats a conclusion beats a claim, because the further along it
 * is the more it costs to have it rest on something unchecked. Socria's own
 * claims are never the target — testing our own reasoning back at them is
 * navel-gazing, and the person did not ask for it.
 */
export function targetOf(p: ProblemModel): ProblemItem | null {
  const mine = (i: ProblemItem) => i.owner === 'user' || i.owner === 'unknown';
  const byKind = (k: ProblemItem['kind']) => p.live.filter((i) => i.kind === k && mine(i)).sort((a, b) => b.turn - a.turn)[0];
  return byKind('decision') ?? byKind('conclusion') ?? byKind('claim') ?? null;
}

/**
 * Premises worth ablating, most informative first.
 *
 * An ASSUMED or UNCHECKED premise that turns out to be load-bearing is the
 * whole point of the exercise, so those go first. A premise the conclusion is
 * already recorded as depending on is next, because confirming a recorded
 * edge is cheap and disconfirming one is valuable. Everything else is
 * background the person is unlikely to thank us for testing.
 */
export function candidates(p: ProblemModel, target: ProblemItem): ProblemItem[] {
  const pool = p.live.filter(
    (i) => i.id !== target.id && i.text.trim().length > 12 && i.kind !== 'question' && i.kind !== 'uncertainty'
  );
  const rank = (i: ProblemItem) => {
    let r = 0;
    if (i.epistemic === 'assumed') r += 4;
    if (i.epistemic === 'needs_verification') r += 3;
    if (i.epistemic === 'inferred') r += 1;
    if (target.dependsOn.includes(i.id)) r += 2;
    if (target.supportedBy.includes(i.id)) r += 2;
    if (i.kind === 'constraint' || i.kind === 'evidence') r += 1;
    return r;
  };
  return pool
    .map((i) => ({ i, r: rank(i) }))
    .filter((x) => x.r > 0)
    .sort((a, b) => b.r - a.r || b.i.turn - a.i.turn)
    .slice(0, MAX_ABLATIONS)
    .map((x) => x.i);
}

/**
 * Run the ablations, in parallel, and keep only what they actually settled.
 *
 * Fails to `null` rather than throwing or guessing: a turn is never worse for
 * this having been unavailable, which is the same failure direction every
 * other optional stage takes (docs/CORE-4-ARCHITECTURE.md §1).
 */
export async function testDependencies(
  apiKey: string,
  p: ProblemModel,
  _state: Pick<CognitiveState, 'currentFocus'>,
  client?: ModelClient
): Promise<Counterfactual | null> {
  const target = targetOf(p);
  if (!target) return null;
  const probe = candidates(p, target);
  if (!probe.length) return null;
  const all = p.live.map((i) => i.text);
  const c = client ?? modelClient(apiKey);

  const runs = await Promise.all(
    probe.map(async (premise): Promise<Ablation | null> => {
      try {
        const remaining = all.filter((t) => t !== premise.text);
        const res = await c.complete({
          role: 'verify',
          model: COGNITION_MODEL,
          temperature: 0,
          json: true,
          system: SYSTEM,
          messages: [{ role: 'user', content: ask(target.text, remaining, premise.text) }],
          maxTokens: 300,
        });
        const v = sanitize(JSON.parse(res.text || '{}'));
        if (v.confidence < CF_FLOOR || v.dependence === 'unclear') return null;
        // A conclusion that "does not follow" with nothing to say about what
        // does is a shrug wearing a verdict's clothes.
        if (v.dependence === 'load_bearing' && !v.instead) return null;
        return {
          premiseId: premise.id,
          premise: premise.text,
          dependence: v.dependence,
          instead: v.instead,
          confidence: v.confidence,
          standing: premise.epistemic,
        };
      } catch {
        return null;
      }
    })
  );

  const ablations = runs.filter((a): a is Ablation => a !== null);
  if (!ablations.length) return null;
  return { conclusion: target.text, conclusionId: target.id, ablations, tested: probe.length };
}

/**
 * What the measurement earned the right to say.
 *
 * Only the load-bearing ones, and only where the premise itself is shaky —
 * "your conclusion depends on a fact you have checked" is true of every sound
 * argument and is not worth a sentence. The valuable shape is narrow: THIS
 * conclusion falls over without THAT, and THAT is an assumption nobody has
 * been back to.
 *
 * Robust results are rendered too, but as one clause, because "it survives
 * without X" is genuinely useful to someone about to go and verify X — it
 * tells them not to bother.
 */
export function renderCounterfactual(cf: Counterfactual | null): string {
  if (!cf) return '';
  const shaky = new Set(['assumed', 'needs_verification', 'inferred', 'unknown']);
  const load = cf.ablations.filter((a) => a.dependence === 'load_bearing');
  const firm = cf.ablations.filter((a) => a.dependence === 'robust' && shaky.has(a.standing));
  if (!load.length && !firm.length) return '';
  const lines: string[] = [];
  for (const a of load.slice(0, 2)) {
    const mark = a.standing === 'assumed' ? ' (which is an assumption, not a finding)' : a.standing === 'needs_verification' ? ' (which nothing has checked)' : '';
    lines.push(`  - Remove "${a.premise}"${mark} and "${cf.conclusion}" no longer follows — instead: ${a.instead}`);
  }
  for (const a of firm.slice(0, 1)) {
    lines.push(`  - "${cf.conclusion}" holds even without "${a.premise}", so that one is not worth chasing.`);
  }
  return (
    `\n=== Tested, not assumed: what this actually rests on ===\n${lines.join('\n')}\n` +
    `This was measured by removing each premise and re-deriving, not inferred from how they wrote it. ` +
    `Where it changes what they should do next, say it plainly and in your own words — what falls over, and what they would have to check to know. ` +
    `Never describe the test, the removal, or that anything was run: they want the finding, not the method.\n`
  );
}
